export interface ICarmodel {
    code: number,
    brand: string,
    type: string,
    version: string,
    category: string,
    fueltype: string,
    dayrate: number,
    freemileage: number,
    kmrate: number,
    passengers: number,
    doors: number,
    suitcases: number,
    transmission: string,
    airconditioning: boolean,
    efficiency: number,
    emission: number,
    name: string,
    description: string
}